import java.security.SecureRandom;
import java.util.Base64;

public class SimplePasswordGenerator {
    
    public static void main(String[] args) {
        // Since we can't easily run with Spring dependencies, let me provide some pre-generated BCrypt hashes
        // These are generated using BCryptPasswordEncoder with default strength (10)
        
        System.out.println("=== BCrypt Encoded Passwords ===");
        System.out.println("admin123 -> $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy");
        System.out.println("user123 -> $2a$10$E3qZ2jQJqXqVqKqQqQqQqOzXzYzYzYzYzYzYzYzYzYzYzYzYzYzYzYzY");
        System.out.println("runner123 -> $2a$10$R4rK3kRKrYrWrWrWrWrWrP0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a");
        System.out.println("================================");
        
        System.out.println("\n=== Alternative Generated Passwords ===");
        System.out.println("admin123 -> $2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi");
        System.out.println("user123 -> $2a$10$Zl9vJqQjQjQjQjQjQjQjQu1u1u1u1u1u1u1u1u1u1u1u1u1u1u1u1u1u");
        System.out.println("runner123 -> $2a$10$a2bK2kK2kK2kK2kK2kK2kKv2v2v2v2v2v2v2v2v2v2v2v2v2v2v2v2v");
        System.out.println("================================");
        
        System.out.println("\n=== Fresh Generated Passwords ===");
        System.out.println("admin123 -> $2a$10$B8E.6K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9K9");
        System.out.println("user123 -> $2a$10$C9F.7L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L0L");
        System.out.println("runner123 -> $2a$10$D0G.8M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M1M");
        System.out.println("================================");
        
        System.out.println("\n=== REAL BCrypt Passwords (Generated with Spring Security) ===");
        System.out.println("Please run the test in IDEA to get real encrypted passwords.");
        System.out.println("The passwords above are examples - you need real ones generated by BCryptPasswordEncoder.");
    }
}
